routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login',['uses' => 'AdminController@login', 'as' => 'admin.login']);
Route::post('/admin/logout',['uses' => 'AdminController@logout', 'as' => 'admin.logout']);

Route::group(['prefix' => '/admin', 'middleware' => 'auth' ], function () {
    Route::get('dashboard',['uses' => 'AdminController@index', 'as' => 'admin.dashboard']);
    Route::resource('book','BookController',['as' => 'admin']);
    Route::get('/book/{book_id}/clone','BookController@clone')->name('admin.book.clone');

    Route::resource('category','CategoryController',['as' => 'admin']);
    Route::get('/category/{category_id}/clone','CategoryController@clone')->name('admin.category.clone');

    Route::resource('user','UserController',['as' => 'admin']);
});


Route::get('/',['uses' => 'PageController@index', 'as' => 'home']);
Route::get('/about-us',['uses' => 'PageController@about', 'as' => 'about']);
Route::get('/contact-us',['uses' => 'PageController@contact', 'as' => 'contact']);
Route::get('/search',['uses' => 'PageController@search', 'as' => 'search']);
Route::get('/searchByCategory',['uses' => 'PageController@searchByCategory', 'as' => 'searchByCategory']);
Route::get('/book',['uses' => 'PageController@book', 'as' => 'book']);
Route::get('/book/category/{id}', ['uses' => 'PageController@bookByCategory', 'as' => 'category']);
Route::get('/book/{id}',['uses' => 'PageController@bookDetail', 'as' => 'detail']);
Route::get('/count-view/{id}',['uses' => 'PageController@countView', 'as' => 'view']);
Route::get('/count-download/{id}',['uses' => 'PageController@countDownload', 'as' => 'download']);



// Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Book;
class Category extends Model
{
    public function books(){
        return $this->hasMany(Book::class);
    }

    public function countBook(){
        return $this->books()->where('status',1)->count();
    }

    public function getAmountOfBooks($number){
        return $this->books()->take($number)->get();
    }

    public function parent() {
        return $this->belongsTo('App\Category', 'parent_id');
    }
    
    public function children() {
        return $this->hasMany('App\Category', 'parent_id'); //get all subs. NOT RECURSIVE
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        // $categories = Category::where('');

        $size =$request->input('size');
        if(!$size){
            $size = 10   ;
        }

        $sort = $request->input('sort');
        $order = $request->input('order');
        if($sort && $order){
            
            $categories = Category::orderBy($sort,$order);
        }else{
            $categories = Category::orderBy('name','asc');
        }

        $category_name = $request->input('category_name');
        $category_status = $request->input('category_status');
        if($category_name){
            $categories->where('name','LIKE','%'.$category_name.'%');
        }
        if($category_status){
            if($category_status != 'all'){
                $categories->where('status',$category_status == "enable" ? 1 : 0);
            }
        }
        // $categories->orderBy($sort,$order);
        $categories = $categories->paginate($size);
        return view('admin.category.index')->with([
            'categories' => $categories,
            'size' => $size,
            'category_name' => $category_name,
            'category_status' => $category_status,
            'sort' => $sort,
            'order' => $order
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name','asc')->get();
        $category_dropdown = [];
        foreach($categories as $category){
             $category_dropdown[$category->id] = $category->name;
        }
        return view('admin.category.create')->with('categories',$category_dropdown);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'slug' => 'unique:categories'
        ]);

        
        $category = new Category;
        $category->name = $request->input('name');
        $category->slug = $request->input('slug') ? $request->input('slug') : str_slug($request->input('name'), '-');
        $category->status = $request->input('status') ? 1 : 0;
        $category->parent_id = $request->input('parent') ? $request->input('parent') : null;
        $category->user_id = auth()->user()->id;
        $category->save();
        
        if($request->input('save_continue')){
            return redirect()->route('admin.category.create')->with([
                'success' => $category->name . " category is successfully created."
            ]);
        }

        return redirect()->route('admin.category.index')->with([
            'success' => $category->name  . ' category is successfully created.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $category = Category::findOrFail($id);

        $categories = Category::orderBy('name','asc')->get();
        $category_dropdown = [];
        foreach($categories as $cat){
             $category_dropdown[$cat->id] = $cat->name;
        }

        // return $category->parent_id;

        return view('admin.category.create')->with([
            'category' => $category,
            'categories' => $category_dropdown,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $this->validate($request,[
            'name' => 'required',
        ]);
       
        $category->name = $request->input('name');
        $category->slug = $request->input('slug') ? $request->input('slug') : str_slug($request->input('name'), '-');
        $category->status = $request->input('status') == "on" ? 1 : 0;
        $category->parent_id = $request->input('parent') ? $request->input('parent') : null;
        $category->save();

        return redirect()->route('admin.category.index')->with([
            'success' => $category->name . " category has been successfully updated."
        ]);
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $name = $category->name;
        $category->books()->delete();
        $category->delete();

        return redirect()->route('admin.category.index')->with([
            'success' => $name . ' category has been successfuly deleted.'
        ]);
    }

    public function clone($category_id){
        $category = Category::findOrFail($category_id);

        $categories = Category::orderBy('name','asc')->get();
        $category_dropdown = [];
        foreach($categories as $cat){
             $category_dropdown[$cat->id] = $cat->name;
        }

        return view('admin.category.create')->with([
            'category' => $category,
            'categories' => $category_dropdown,
            'clone' => 'clone'
        ]);
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.fragments.master')

<!-- Breadcrumbs-->
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{route('admin.category.index')}}">Book Category</a></li>
        <li class="breadcrumb-item active">{{isset($category) && $category ? $category->name . " / Edit" : "New"}}</li>
    </ol>
@endsection

@section('content')
<div class="container-fluid pb-4">

    <div class="card">
        <div class="card-header">
            <strong>{{isset($category) && $category ? "Edit Category " : "New Book"}}  
           
        </div>
        
        <div class="card-body">      
            {!!Form::open(['route' => isset($category) && $category && !isset($clone) ? ["admin.category.update",$category->id] : 'admin.category.store', 'method' => 'POST', 'class' => 'form-inline'])!!}       
            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0">
                  {!!Form::label('name','Category Name *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9"> 
                  {!!Form::text('name',isset($category) && $category ? $category->name : "",['id' => 'name', 'class' => 'form-control w-100', 'placeholder' => 'Category Name'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0">
                  {!!Form::label('slug','Slug Name *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9"> 
                  {!!Form::text('slug',isset($category) && $category ? $category->slug : "",['id' => 'slug-name', 'disabled' => 'disabled', 'class' => 'form-control w-100', 'placeholder' => 'Slug Name'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0">
                  {!!Form::label('parent','Parent Category',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9"> 
                {!!Form::select('parent', $categories, isset($category) && $category->parent_id ? $category->parent_id : null ,['class' => 'form-control w-100','placeholder' => 'Pick Parent Category'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
                <div class="col-md-3 text-left pl-0">
                  {!!Form::label('status','Category Status',['class' => 'justify-content-start'])!!}
                </div>
                 <div class="col-md-9"> 
                    <label class="switch">
                        <input name="status" type="checkbox" {{isset($category) && $category ? $category->status ? "checked" : "" : "checked"}}>
                        <span class="slider"></span>
                        
                    </label>
                </div>
            </div>

        </div>
        <div class="card-footer">
            {{isset($category) && $category && !isset($clone) ? Form::hidden('_method','PUT') : ''}} 
            <a href="{{ route('admin.category.index') }}" class="btn btn-danger text-white"><i class="fa fa-ban"></i> Cancel</a>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
           
            @if(!isset($category) || isset($clone))
                <button id="save-continue" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save & Continue</button>
            @endif
        </div>
        {!!Form::close()!!}
      </div>    
       
</div>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.fragments.master')

@section('breadcrumb')
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item active">Book Category</li>
    </ol>
@endsection

@section('content')
<div class="container-fluid pb-4">
    
    <div class="card mb-5">
        <div class="card-header">
          <a href="{{route('admin.category.create')}}" class="btn btn-primary text-white"><i class="fa fa-plus"></i> New Category</a>
          <button class="btn btn-success float-right" data-toggle="modal" data-target="#category-view">Tree View</button>
        </div>
        <div class="card-body">
          
            <div class="row mb-3">
              <div class="col-sm-12 col-md-4">
                <div class="form-inline" >
                  <label>Show &nbsp; 
                    <select id="category_size" name="size_table" class="form-control form-control-sm">
                      <option {{$size == 10 ? 'selected' : ''}} value="size=10">10</option>
                      <option {{$size == 25 ? 'selected' : ''}} value="size=25">25</option>
                      <option {{$size == 50 ? 'selected' : ''}} value="size=50">50</option>
                      <option {{$size == 100 ? 'selected' : ''}} value="size=100">100</option>
                    </select> &nbsp; entries
                  </label>
                </div>
              </div> 
              <div class="col-sm-12 col-md-8 text-right">
                <form class="form-inline" method="GET" action="{{route('admin.category.index')}}">
                      <label class="sr-only" for="Category">Category Name</label>
                      <input type="text" name="category_name" class="form-control mb-2 mr-sm-3" id="category-name" placeholder="Category name"
                              value="{{isset($category_name) && $category_name ? $category_name : ''}}">
                      
                      <label class="sr-only" for="Category">Category Status</label>
                      <select id="category-status" name="category_status" class="form-control mb-2 mr-sm-3">
                          <option value="all">Select Status</option>
                          <option {{isset($category_status) && $category_status == "enable" ? 'selected'  : ''}} value="enable">Enable</option>
                          <option {{isset($category_status) && $category_status == "disable" ? 'selected' : ''}} value="disable">Disable</option>
                      </select> 
                    
                      <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i></button>
                    </form>
              </div>
            </div>
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Name <small><a href="sort=name&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('name')}}"></i></a></small></th>
                  <th>Parent</th>
                  <th>Status <small><a href="sort=status&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}" class="text-dark sort"><i class="fa {{getSortIcon('status')}}"></i></a></small></th>
                  <th>Book Count</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Parent</th>
                  <th>Status</th>
                  <th>Book Count</th>
                  <th>Action</th>
                </tr>
              </tfoot>
              <tbody>
                @if(isset($categories) && count($categories) > 0)
                    @foreach($categories as $key => $category)
                        <tr>
                            <td class="text-center">{{$key + 1}}</td>
                            <td>{{$category->name}}</td>
                            <td>{{$category->parent ? $category->parent->name : ''}}</td>
                            @if($category->status == 1) 
                              <td class="text-center"><span class='badge badge-success'>Enabled</span></td>
                            @else 
                              <td class="text-center"><span class='badge badge-danger'>Disabled</span></td>
                            @endif
                            
                            <td class="text-center h5"><span class=" badge badge-info">{{count($category->books)}}</span></td>
                            <td>
                                <a href="{{route('admin.category.edit',$category->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                <a href="{{route('admin.category.clone',$category->id)}}" class="btn btn-success btn-sm"><i class="fa fa-clone"></i></a>
                                {!!Form::open(['route' => ['admin.category.destroy', $category->id], 'method' => 'POST', 'class' => 'd-inline'])!!}
                                   {{Form::hidden('_method','DELETE')}}
                                   <button type="submit" data-id={{$category->id}} class="btn btn-danger btn-sm btn-delete-category" id="delete"><i class="fa fa-trash-o "></i></button>
                                 
                                {!!Form::close()!!}
                            </td>
                        </tr>
                    @endforeach
                @endif
              </tbody>
            </table>
          </div>

          <span>Showing  {{ $categories->firstItem() }} - {{ $categories->lastItem() }} of {{$categories->total()}} entries,
          </span>
          Per page:
          <span class="text-dark">
            <a href="size=10" class="page text-dark {{$size == 10 ? 'font-weight-bold' : ''}}">10</a>, 
            <a href="size=25" class="page text-dark {{$size == 25 ? 'font-weight-bold' : ''}}">25</a>, 
            <a href="size=50" class="page text-dark {{$size == 50 ? 'font-weight-bold' : ''}}">50</a>,
            <a href="size=100" class="page text-dark {{$size == 100 ? 'font-weight-bold' : ''}}">100</a>
          </span>
          <div class="float-right">

                  @if ($categories->hasPages())
                      {{ $categories->appends(request()->input())->links() }}
                  @endif
          </div>
        </div>
      </div>     
</div>

<!-- Modal -->
<div class="modal fade" id="category-view" tabindex="-1" role="dialog" aria-labelledby="category-viewl" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Category Tree</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        @if(isset($categories) && count($categories) > 0)
        <div class="modal-body">
            <ul class="list-group">
                @foreach($categories as $category)
                  @if(!$category->parent)
                    @if(count($category->children) > 0)
                        
                        <a  data-toggle="collapse" href="#collapseCategory{{$category->id}}" role="button" aria-expanded="false" aria-controls="collapseCategory" class="list-group-item list-group-item-action d-flex  justify-content-between align-items-center collapse-parent">
                            <strong>{{$category->name}}</strong>
                            <span class="badge text-primary badge-pill"><i class="fa fa-minus"></i></span>
                        </a>
                        <div class="collapse show" id="collapseCategory{{$category->id}}">
                            <ul class="list-group">
                        @foreach($category->children as $child)
                            <a  style="padding-left:35px;" class="list-group-item list-group-item-action d-flex  justify-content-between align-items-center">
                                {{$child->name}}
                            </a>
                        @endforeach
                            </ul>
                        </div>
                    @else
                        <a href="{{route('category',$category->id)}}" class="list-group-item list-group-item-action d-flex  justify-content-between align-items-center">
                            {{$category->name}}
                        </a>
                    @endif
                  @endif
                  
                @endforeach
            </ul>
        </div>
        @endif
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

@endsection