routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login',['uses' => 'AdminController@login', 'as' => 'admin.login']);
Route::post('/admin/logout',['uses' => 'AdminController@logout', 'as' => 'admin.logout']);

Route::group(['prefix' => '/admin', 'middleware' => 'auth' ], function () {
    Route::get('dashboard',['uses' => 'AdminController@index', 'as' => 'admin.dashboard']);
    Route::resource('book','BookController',['as' => 'admin']);
    Route::get('/book/{book_id}/clone','BookController@clone')->name('admin.book.clone');

    Route::resource('category','CategoryController',['as' => 'admin']);
    Route::get('/category/{category_id}/clone','CategoryController@clone')->name('admin.category.clone');

    Route::resource('user','UserController',['as' => 'admin']);
});


Route::get('/',['uses' => 'PageController@index', 'as' => 'home']);
Route::get('/about-us',['uses' => 'PageController@about', 'as' => 'about']);
Route::get('/contact-us',['uses' => 'PageController@contact', 'as' => 'contact']);
Route::get('/search',['uses' => 'PageController@search', 'as' => 'search']);
Route::get('/searchByCategory',['uses' => 'PageController@searchByCategory', 'as' => 'searchByCategory']);
Route::get('/book',['uses' => 'PageController@book', 'as' => 'book']);
Route::get('/book/category/{id}', ['uses' => 'PageController@bookByCategory', 'as' => 'category']);
Route::get('/book/{id}',['uses' => 'PageController@bookDetail', 'as' => 'detail']);
Route::get('/count-view/{id}',['uses' => 'PageController@countView', 'as' => 'view']);
Route::get('/count-download/{id}',['uses' => 'PageController@countDownload', 'as' => 'download']);



// Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Category;
class Book extends Model
{
    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Category;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic as Image;


class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $category_id = '';
        $size =$request->input('size');
        if(!$size){
            $size = 10   ;
        }

        $sort = $request->input('sort');
        $order = $request->input('order');
        if($sort && $order){
            $books = Book::orderBy($sort,$order);
        }else{
            $books = Book::orderBy('created_at','desc');
        }

        $search = $request->input('search');
        $book_category = $request->input('book_category');
        $book_status = $request->input('book_status');

        $books->where(function($book) use ($search){
                $book->orWhere('title','LIKE','%'.$search.'%')
                ->orWhere('author','LIKE', '%'.$search.'%')
                ->orWhere('published_year','LIKE', '%'.$search.'%');
            });
              
        if($book_category!= null){
            if($book_category != 'all'){
                $category = Category::where('name',$book_category)->first();
                $category_id = $category->id;
                $books->where('category_id',$category->id);
            }   
        } 

        if($book_status != null){
            if($book_status != 'all'){
                $books->where('status',$book_status == "enable" ? 1 : 0);
             } 
        }    
            
        
        $books = $books->paginate($size);
        $categories = Category::orderBy('name','asc')->get();
        return view('admin.book.index')->with([
            'books' => $books,
            'book_category' => $category_id,
            'categories' => $categories,
            'size' => $size,
            'search' => $search,
            'book_status' => $book_status,
            'sort' => $sort,
            'order' => $order
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('status',1)->orderBy('name','asc')->get();
        $category_dropdown = [];
        foreach($categories as $category){
             if(count($category->children) == 0)
             $category_dropdown[$category->id] = $category->name;
        }
        // return $category_dropdown;
        return view('admin.book.create')->with([
            'categories' => $category_dropdown
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'slug' => 'unique:books',
            'author' => 'required',
            'category' => 'required',
            'published' => 'required | numeric',
            'image' => 'image | mimes:jpg,jpeg,png',
            'file' => 'required|max:10000'
        ]);

        if($request->hasFile('image')){
            $image = $request->file('image');

            $imageNameWithExt = $image->getClientOriginalName();

            $imageName = pathInfo($imageNameWithExt,PATHINFO_FILENAME);

            $extension = $image->getClientOriginalExtension();

            $newImageName = $imageName.'_'.time().'.'.$extension;

            $pathImage = $image->storeAs('public/images',$newImageName);

            // Resize

            $thumbnailpath = public_path('storage/images/'.$newImageName);

            Image::make($thumbnailpath)->resize(250, 350)->save($thumbnailpath);

        }else{
            $newImageName = 'default.png';
        }

        if($request->hasFile('file')){
            $file = $request->file('file');

            $fileNameWithExt = $file->getClientOriginalName();

            $fileName = pathInfo($fileNameWithExt,PATHINFO_FILENAME);

            $extension = $file->getClientOriginalExtension();

            $newFileName = $fileName.'.'.$extension;

            $pathFile = $file->storeAs('public/files',$newFileName);
        }

        $book = new Book;
        $book->title = $request->input('title');
        $book->slug = $request->input('slug') ? $request->input('slug') : str_slug($request->input('title'), '-');
        $book->author = $request->input('author');
        $book->category_id = $request->input('category');
        $book->description = $request->input('description');
        $book->published_year = $request->input('published');
        $book->image = $newImageName;
        $book->file = $newFileName;
        $book->status = $request->input('status') == "on" ? 1 : 0;
        $book->user_id = auth()->user()->id;
        $book->view = 0;
        $book->download = 0;

        $book->save();

        if($request->input('save_continue')){
            return redirect()->route('admin.book.create')->with([
                'success' => $book->title . " book has been created."
            ]);
        }

        return redirect()->route('admin.book.index')->with([
            'success' => $book->title . " book has been created."
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::where('status',1)->orderBy('name','asc')->get();
        $category_dropdown = [];
        foreach($categories as $category){
            if(count($category->children) == 0)
             $category_dropdown[$category->id] = $category->name;
        }

        $book = Book::findOrFail($id);

        return view('admin.book.create')->with([
            'book' => $book,
            'categories' => $category_dropdown
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required',
            'author' => 'required',
            'published' => 'required | numeric',
            'image' => 'image | mimes:jpg,jpeg,png',
            'file' => 'max:10000'
        ]);

        $newImageName = '';
        $newFileName = '';
        if($request->hasFile('image')){
            $image = $request->file('image');

            $imageNameWithExt = $image->getClientOriginalName();

            $imageName = pathInfo($imageNameWithExt,PATHINFO_FILENAME);

            $extension = $image->getClientOriginalExtension();

            $newImageName = $imageName.'_'.time().'.'.$extension;

            $pathImage = $image->storeAs('public/images',$newImageName);

            // Resize

            $thumbnailpath = public_path('storage/images/'.$newImageName);

            Image::make($thumbnailpath)->resize(250, 350)->save($thumbnailpath);
        }

        if($request->hasFile('file')){
            $file = $request->file('file');

            $fileNameWithExt = $file->getClientOriginalName();

            $fileName = pathInfo($fileNameWithExt,PATHINFO_FILENAME);

            $extension = $file->getClientOriginalExtension();

            $newFileName = $fileName.'.'.$extension;

            $pathFile = $file->storeAs('public/files',$newFileName);
        }

        $book = Book::findOrFail($id);
        $book->title = $request->input('title');
        $book->slug = $request->input('slug') ? $request->input('slug') : str_slug($request->input('title'), '-');
        $book->author = $request->input('author');
        $book->category_id = $request->input('category');
        $book->description = $request->input('description');
        $book->published_year = $request->input('published');
        if($newImageName) $book->image = $newImageName;
        if($newFileName) $book->file = $newFileName;
        $book->status = $request->input('status') == "on" ? 1 : 0;

        $book->save();

        return redirect()->route('admin.book.index')->with([
            'success' => $book->title . " book has been successfully updated."
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $book = Book::findOrFail($id);
        $name = $book->title;
        $book->delete();

        return redirect()->route('admin.book.index')->with([
            'success' => $name . ' book has been successfuly deleted.'
        ]);
    }

    public function clone($book_id){
        $categories = Category::where('status',1)->orderBy('name','asc')->get();
        $category_dropdown = [];
        foreach($categories as $category){
            if(count($category->children) == 0)
             $category_dropdown[$category->id] = $category->name;
        }

        $book = Book::findOrFail($book_id);

        return view('admin.book.create')->with([
            'book' => $book,
            'categories' => $category_dropdown,
            'clone' => 'clone'
        ]);
    }
}

resources/views/admin/book/create.blade.php
@extends('admin.fragments.master')

@section('breadcrumb')
<!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{route('admin.book.index')}}">Book</a></li>
        <li class="breadcrumb-item active">{{isset($book) && $book ? $book->title . " / Edit" : "New"}}</li>
    </ol>
@endsection

@section('content')
<div class="container-fluid pb-4">
    <div class="card mb-5">
        <div class="card-header">
          <strong>New Book</strong>  
        </div>
        <div class="card-body ">
          {!!Form::open(['route' => isset($book) && $book && !isset($clone) ? ['admin.book.update',$book->id] : 'admin.book.store', 'method' => 'POST', 'class' => 'form-inline', 'files' => true])!!}
            
            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('title','Book Title *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('title', isset($book) && $book ? $book->title : '',['id' => 'name','class' => 'form-control w-100', 'placeholder' => 'Book Title'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('slug','Slug Title *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('slug', isset($book) && $book ? $book->slug : '',['id' => 'slug-name', 'disabled' => 'disabled' ,'class' => 'form-control w-100', 'placeholder' => 'Slug Title'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('category','Book Category *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::select('category', $categories, isset($book) && $book ? $book->category->id : null ,['class' => 'form-control w-100'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('author','Book Author *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('author',isset($book) && $book ? $book->author : '',['class' => 'form-control w-100', 'placeholder' => 'Book Author'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('published','Book Published Year *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('published',isset($book) && $book ? $book->published_year : '',['class' => 'form-control w-100', 'placeholder' => 'Book Published Year'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('description','Book Description',['class' => 'd-flex align-items-start justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::textarea('description', isset($book) && $book ? $book->description : '', ['size' => '30x7','class' => 'form-control w-100', 'id' => 'summernote'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('image','Book Image',['class' => 'd-flex justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0 text-center"> 
                <img id="image-upload" src="{{asset(isset($book) && !isset($clone)? 'storage/images/'.$book->image : 'assets/images/250x350.png')}}">
                <input name="image" type="file" id="image" class="d-none">  
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('file','Book File *',['class' => 'd-flex justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                <input id="file" type="file" name="file" class="d-none" value={{ isset($book) && !isset($clone) ? '/storage/files/'.$book->file : "No file chosen"}}/>
                <button id="file-upload" class="btn btn-info btn-sm mr-2">Choose File</button><span id="file-name">{{isset($book) && !isset($clone) ? $book->file : "No file chosen"}}</span>
              </div>
            </div>
            
            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0 pr-0">
                  {!!Form::label('status','Book Status *',['class' => 'justify-content-start'])!!}
                </div>
                 <div class="col-md-9 pl-0 pr-0"> 
                    <label class="switch">
                        <input name="status" type="checkbox" {{isset($book) && $book ? $book->status ? "checked" : "" : "checked"}}>
                        <span class="slider"></span>
                        
                    </label>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="{{ route('admin.book.index') }}" class="btn btn-danger text-white"><i class="fa fa-ban"></i> Cancel</a>
            {{isset($book) && $book && !isset($clone)? Form::hidden('_method','PUT') : ''}} 
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
            @if(!isset($book) || isset($clone))
                <button id="save-continue" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save & Continue</button>
            @endif
        </div>
        {!!Form::close()!!}
      </div>     
</div>
@endsection

resources/views/admin/book/index.blade.php
@extends('admin.fragments.master')

@section('breadcrumb')
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Book</li>
</ol>
@endsection

@section('content')
<div class="container-fluid pb-4">
    <div class="card mb-5">
        <div class="card-header">
          <a href="{{route('admin.book.create')}}" class="btn btn-primary text-white"><i class="fa fa-plus"></i> New Book</a>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-sm-12 col-md-4">
                  <div class="form-inline" >
                    <label>Show &nbsp; 
                      <select id="category_size" name="size_table" class="form-control form-control-sm">
                        <option {{$size == 10 ? 'selected' : ''}} value="size=10">10</option>
                        <option {{$size == 25 ? 'selected' : ''}} value="size=25">25</option>
                        <option {{$size == 50 ? 'selected' : ''}} value="size=50">50</option>
                        <option {{$size == 100 ? 'selected' : ''}} value="size=100">100</option>
                      </select> &nbsp; entries
                    </label>
                  </div>
                </div> 
                <div class="col-sm-12 col-md-8 text-right">
                  <form class="form-inline" method="GET" action="{{route('admin.book.index')}}">
                        <label class="sr-only" for="book_name">Book Title</label>
                        <input type="text" name="search" class="form-control mb-2 mr-sm-3" id="book-name" placeholder="Search for ..."
                                value="{{isset($search) && $search ? $search : ''}}">
                        
                        <label class="sr-only" for="status">Category</label>
                        <select id="book-status" name="book_category" class="form-control mb-2 mr-sm-3">
                            <option value="all">Category</option>
                            @foreach($categories as $category)
                              <option {{isset($book_category) && $book_category == $category->id ? 'selected' : ''  }} value="{{$category->name}}">{{$category->name}}</option>  
                            @endforeach
                        </select> 

                        <label class="sr-only" for="status">Status</label>
                        <select id="book-status" name="book_status" class="form-control mb-2 mr-sm-3">
                            <option value="all">Status</option>
                            <option {{isset($book_status) && $book_status == "enable" ? 'selected'  : ''}} value="enable">Enable</option>
                            <option {{isset($book_status) && $book_status == "disable" ? 'selected' : ''}} value="disable">Disable</option>
                        </select> 
                      
                        <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i></button>
                      </form>
                </div>
              </div>
          <div class="table-responsive">
            <table class="table table-bordered  table-hover">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Title <small><a href="sort=title&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('title')}}"></i></a></small></th>
                  <th>Category </th>
                  <th>Author <small><a href="sort=author&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('author')}}"></i></a></small></th>
                  <th>Year <small><a href="sort=published_year&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('published_year')}}"></i></a></small></th>
                  <th>Status <small><a href="sort=status&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('status')}}"></i></a></small></th>
                  <th>View</th>
                  <th>Down</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Title</th>
                  <th>Category</th>
                  <th>Author</th>
                  <th>Year</th>
                  <th>Status</th>
                  <th>View</th>
                  <th>Down</th>
                  <th>Action</th>
                </tr>
              </tfoot>
              <tbody>
                @if(isset($books) && count($books) > 0)
                    @foreach($books as $key => $book)
                        <tr>
                            <td class="text-center">{{$key + 1}}</td>
                            <td>{{$book->title}}</td>
                            <td>{{$book->category->name}}</td>
                            <td>{{$book->author}}</td>
                            <td>{{$book->published_year}}</td>
                            @if($book->status == 1) 
                              <td class="text-center"><span class='badge badge-success'>Enabled</span></td>
                            @else 
                              <td class="text-center"><span class='badge badge-danger'>Disabled</span></td>
                            @endif
                            <td class="text-center h5"><span class='badge badge-info'>{{$book->view}}</span></td>
                            <td class="text-center h5"><span class='badge badge-info'>{{$book->download}}</span></td>
                            <td>
                                <a href="{{route('admin.book.edit',$book->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                <a href="{{route('admin.book.clone',$book->id)}}" class="btn btn-success btn-sm"><i class="fa fa-clone"></i></a>
                                {!!Form::open(['route' => ['admin.book.destroy', $book->id], 'method' => 'POST', 'class' => 'd-inline'])!!}
                                   {{Form::hidden('_method','DELETE')}}
                                   <button type="submit" data-id={{$book->id}}  class="btn btn-danger btn-sm btn-delete-book" ><i class="fa fa-trash-o "></i></button>
                                 
                                {!!Form::close()!!}
                              </td>
                        </tr>
                    @endforeach
                @endif
              </tbody>
            </table>
          </div>
          <span>Showing  {{ $books->firstItem() }} - {{ $books->lastItem() }} of {{$books->total()}} entries,
            </span>
            Per page:
            <span class="text-dark">
              <a href="size=10" class="page text-dark {{$size == 10 ? 'font-weight-bold' : ''}}">10</a>, 
              <a href="size=25" class="page text-dark {{$size == 25 ? 'font-weight-bold' : ''}}">25</a>, 
              <a href="size=50" class="page text-dark {{$size == 50 ? 'font-weight-bold' : ''}}">50</a>,
              <a href="size=100" class="page text-dark {{$size == 100 ? 'font-weight-bold' : ''}}">100</a>
            </span>
            <div class="float-right">
  
                    @if ($books->hasPages())
                        {{ $books->appends(request()->input())->links() }}
                    @endif
            </div>
        </div>
      </div>     
</div>
@endsection