routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login',['uses' => 'AdminController@login', 'as' => 'admin.login']);
Route::post('/admin/logout',['uses' => 'AdminController@logout', 'as' => 'admin.logout']);

Route::group(['prefix' => '/admin', 'middleware' => 'auth' ], function () {
    Route::get('dashboard',['uses' => 'AdminController@index', 'as' => 'admin.dashboard']);
    Route::resource('book','BookController',['as' => 'admin']);
    Route::get('/book/{book_id}/clone','BookController@clone')->name('admin.book.clone');

    Route::resource('category','CategoryController',['as' => 'admin']);
    Route::get('/category/{category_id}/clone','CategoryController@clone')->name('admin.category.clone');

    Route::resource('user','UserController',['as' => 'admin']);
});


Route::get('/',['uses' => 'PageController@index', 'as' => 'home']);
Route::get('/about-us',['uses' => 'PageController@about', 'as' => 'about']);
Route::get('/contact-us',['uses' => 'PageController@contact', 'as' => 'contact']);
Route::get('/search',['uses' => 'PageController@search', 'as' => 'search']);
Route::get('/searchByCategory',['uses' => 'PageController@searchByCategory', 'as' => 'searchByCategory']);
Route::get('/book',['uses' => 'PageController@book', 'as' => 'book']);
Route::get('/book/category/{id}', ['uses' => 'PageController@bookByCategory', 'as' => 'category']);
Route::get('/book/{id}',['uses' => 'PageController@bookDetail', 'as' => 'detail']);
Route::get('/count-view/{id}',['uses' => 'PageController@countView', 'as' => 'view']);
Route::get('/count-download/{id}',['uses' => 'PageController@countDownload', 'as' => 'download']);



// Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/index.blade.php
@extends('admin.fragments.master')

@section('content')
<div class="container-fluid mt-5">
<!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('admin.dashboard')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">My Dashboard</li>
    </ol>
    <!-- Icon Cards-->
      <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
          <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-book"></i>
              </div>
                <div class="mr-5">{{$total['book']}} Books!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="{{route('admin.book.index')}}">
              <span class="float-left">View Details</span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
          <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-list"></i>
              </div>
              <div class="mr-5">{{$total['category']}} Book Categories!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="{{route('admin.category.index')}}">
              <span class="float-left">View Details</span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>

        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-info o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fa fa-fw fa-users"></i>
                </div>
                <div class="mr-5">{{$total['user']}} Users!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="{{route('admin.user.index')}}">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
      </div>      
</div>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<title>
    {{config('app.name','BookStore')}}
</title>
@include('admin.fragments.head')
</head>
<body class="bg-dark"
<div class="container">
  <div class="text-center text-white mt-5">
      <h1>{{config('app.name','BookStore')}}</h1>
  </div>
    <div class="card card-login mx-auto mt-3">
      <div class="card-header">{{ __('Login') }}</div>
      <div class="card-body">
        <form method="POST" action="{{ route('login') }}" aria-label="{{ __('Login') }}">
          @csrf
          <div class="form-group">
            <label for="email">{{ __('E-Mail Address') }}</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>

               @if ($errors->has('email'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('email') }}</strong>
                </span>
              @endif
          </div>
          <div class="form-group">
            <label for="password">{{ __('Password') }}</label>
            <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

               @if ($errors->has('password'))
                   <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
                @endif
          </div>
          <div class="form-group">
            <div class="form-check">
              <label class="form-check-label">
                  <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> {{ __('Remember Me') }}
            </div>
          </div>
          <button type="submit" class="btn btn-primary">
              {{ __('Login') }}
          </button>
        </form>
      </div>
    </div>
  </div> 
</body>
@include('admin.fragments.scripts')